### ISSUE TITLE
Give a list of easy, medium, hard problems (10 of each type with max acceptance) on Leetcode for interview preparation

### ISSUE THREAD

**Issue by Almond65** [Almond65/hacktoberfest#11]

**Comment by Kesav890** [comment]
can i have this issue?

**Comment by Anubhakri13** [comment]
Hello @Almond65 , May you assign this to me?

**Comment by Almond65** [comment]
@Kesav890  assigned

**Comment by Almond65** [comment]
@Anubhakri13 assigned

**Comment by CarefoDragneel** [comment]
I have solved 280+ questions on leetcode. Please can you assign this issue to me as well?

**Comment by Almond65** [comment]
@CarefoDragneel assigned

**Comment by arushitrivedi** [comment]
Hey @Almond65 can I work on this issue and make useful contributions to the project? Please assign it to me!!
