### ISSUE TITLE
Write a program to to count the number of set bits in a binary number

### ISSUE THREAD

**Issue by Almond65** [Almond65/hacktoberfest#12]

**Comment by Yash-Goyal007** [comment]
I want to work on this issue. Please assign this to me...

**Comment by Almond65** [comment]
@Yash-Goyal007 assigned...Do explain the algorithm u used if possible or add a link to a certain site

**Comment by Naisargika1402** [comment]
I have the code to this problem with me also with comments to explain it. Can you please assign it to me?

**Comment by raginiisingh** [comment]
I can write a proper solution to the above question with explanatory comments. Can you please assign this to me?

**Comment by Almond65** [comment]
Go ahead

**Comment by arkapg211002** [comment]
@Almond65 hey i would like to contribute ,pls assign me

**Comment by Almond65** [comment]
assigned
