### ISSUE TITLE
Share links to good free courses for learning devOps

### ISSUE THREAD

**Issue by Almond65** [Almond65/hacktoberfest#13]

**Comment by Aishubalaji** [comment]
Hey, Can I take this issue? @Almond65

**Comment by Almond65** [comment]
@Aishubalaji Yes Go ahead!!

**Comment by Almond65** [comment]
@Aishubalaji Give brief description about the courses too and their plus points ...u can give your own opinion about roadmaps and all ...The .md file should look good

**Comment by Aishubalaji** [comment]
Well, I don't know much about devops, but i will try my best!.

**Comment by Almond65** [comment]
Ok
