### ISSUE TITLE
Want to do 9th question of difficulty : easy question ( Cells with Odd Values in a Matrix )

### ISSUE THREAD

**Issue by Swarup-2003** [Almond65/hacktoberfest#32]
Please assign me to do the code . I did it please merge it .

**Comment by Almond65** [comment]
@Swarup-2003 done

**Comment by Swarup-2003** [comment]
Thnx a lot . It is my first hacktoberfest event and I want to complete it
anyways . You help me a lot .

**Comment by Almond65** [comment]
@Swarup-2003 👍
