### ISSUE TITLE
Write a program to print Nth even number

### ISSUE THREAD

**Issue by Almond65** [Almond65/hacktoberfest#4]

**Comment by destroyer5067** [comment]
Hey , @Almond65  assign this issue to me

**Comment by Gulshan-11** [comment]
Hey, @Almond65 assign this issue to me

**Comment by Almond65** [comment]
@Gulshan-11 @destroyer5067 assigned

**Comment by arkapg211002** [comment]
@Almond65 hey i would like to contribute ,pls assign me

**Comment by Almond65** [comment]
assigned
